version: 2

models:
  - name: stg_players
    columns:
      - name: player_season_id
        tests:
          - unique
          - not_null
      - name: player_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: league_id
        tests:
          - not_null
      - name: season
        tests:
          - not_null
          - is_between:
              arguments:
                min_value: 2020
                max_value: 2026
      - name: minutes
        tests:
          - not_null
          - is_between:
              arguments:
                min_value: 300
      - name: rating
        tests:
          - is_between:
              arguments:
                min_value: 0
                max_value: 10
      - name: passes_accuracy_pct
        tests:
          - is_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: goals
        tests:
          - non_negative
      - name: assists
        tests:
          - non_negative
      - name: shots_total
        tests:
          - non_negative
      - name: shots_on_target
        tests:
          - non_negative
      - name: passes_total
        tests:
          - non_negative
      - name: passes_key
        tests:
          - non_negative
      - name: tackles_total
        tests:
          - non_negative
      - name: duels_total
        tests:
          - non_negative
      - name: duels_won
        tests:
          - non_negative
      - name: dribbles_attempts
        tests:
          - non_negative
      - name: dribbles_success
        tests:
          - non_negative
      - name: fouls_drawn
        tests:
          - non_negative
      - name: fouls_committed
        tests:
          - non_negative
      - name: cards_yellow
        tests:
          - non_negative
      - name: cards_red
        tests:
          - non_negative
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - team_id
              - league_id
              - season
      - accepted_values:
          arguments:
            column_name: league_id
            values: [39, 61, 78, 135, 140]
