version: 2

models:
  - name: dim_players
    columns:
      - name: player_id
        tests:
          - unique
          - not_null

  - name: dim_teams
    columns:
      - name: team_id
        tests:
          - unique
          - not_null
      - name: team_name
        tests:
          - not_null

  - name: dim_leagues
    columns:
      - name: league_id
        tests:
          - unique
          - not_null
      - name: league_name
        tests:
          - not_null
